### ISSUE TITLE
Shifted forward and reverse dip

### ISSUE THREAD

**Issue by alexg9010** [slowkow/CENTIPEDE.tutorial#4]
Hi,

First of all this introduction you wrote helped me a lot to understand the data required for use with centipede!

I currently using your package for my master's thesis and now i have a problem where you might be able to help me. 

As you might see in the plot below the significant dip in dnase-cut probability does not overlap in forward and reverse strand. And i think this shift happened in the centipede_data function in your package. 

My read length is 35 and that seems to have something to do with the shift.

Maybe you could help me to resolve this problem.
 
![sp4_full](https://cloud.githubusercontent.com/assets/14021775/15114063/63579fbe-15f8-11e6-83fa-ff91126c0759.png)

Thanks in advance 
Alex

**Comment by slowkow** [comment]
Thanks for opening this issue! I'd like to help you resolve this. I also noticed this strange shift in my own plot. The blue line is shifted to the right, relative to the red line. This is similar to your plot.

![image](https://cloud.githubusercontent.com/assets/209714/15114557/866380c0-15c8-11e6-82b0-06bb06ca3910.png)

I wonder if I have a bug in the `centipede_data()` function. I'll try to have a look at the code in the next few days or weeks, but I need some time. I'd be very happy to review and accept a pull request about this!

**Comment by alexg9010** [comment]
made up a pull request

**Comment by danrlu** [comment]
First of all thank you for the tutorial and package, it's extremely helpful!!

I came across the same thing. I wonder whether this is the issue:
```{r}
library(CENTIPEDE.tutorial)

region=parse_region("2L:10-20")
region_len <- abs(region$end - region$start) + 1

item=list(strand=as.factor(c("+","+","-","-")),  pos=as.integer(c(15,25,2,12)),qwidth=as.integer(c(10,10,10,10)))

################### copied from functions.R line 152-173 ###############

# take care of negative reads starting at end position
neg_shift <- item$qwidth * as.numeric(item$strand == "-")
item$pos <- item$pos + neg_shift

idx <- item$pos >= region$start & item$pos <= region$end
if (sum(idx) == 0) {
  return(rep(0, 2 * region_len))
}
strand <- item$strand[idx]
position <- item$pos[idx]

# Create a row that represents the flanking region surrounding a site,
# each column is a nucleotide position relative to the center of the motif
# match.
# The values in this matrix are the number of read start sites that occur
# at that position.
# Since we have two strands, the first half of the matrix represents the
# positive strand and the second have represents the negative strand.
is.neg <- as.numeric(strand == "-")
j <- 1 + position - min(position) + (region_len * is.neg)

as.numeric(table(factor(j, levels = seq(1, 2 * region_len))))

#########################################################
```

Would this work better? So the matrix of counts is centered around the motif:
```{r}
j <- 1 + position - region$start + (region_len * is.neg)
as.numeric(table(factor(j, levels = seq(1, 2 * region_len))))
```
